// Tableau des métiers disponibles dans l'application
// Chaque objet dans le tableau représente un métier avec une étiquette
export const metiers = [
  { label: "Boucher" },
  { label: "Boulanger" },
  { label: "Carreleur" },
  { label: "Charpentier" },
  { label: "Chauffagiste" },
  { label: "Chocolatier" },
  { label: "Ciseleur" },
  { label: "Cordonnerie" },
  { label: "Coutelier" },
  { label: "Cuisinier" },
  { label: "Ébéniste" },
  { label: "Électricien" },
  { label: "Esthéticien(ne)" },
  { label: "Ferronnier" },
  { label: "Fleuriste" },
  { label: "Forgeron" },
  { label: "Graveur" },
  { label: "Horloger" },
  { label: "Imprimeur" },
  { label: "Installateur sanitaire" },
  { label: "Jardinier-paysagiste" },
  { label: "Maçon" },
  { label: "Menuisier" },
  { label: "Mécanicien automobile" },
  { label: "Modiste" },
  { label: "Orfèvre" },
  { label: "Pâtissier" },
  { label: "Peintre en bâtiment" },
  { label: "Photographe" },
  { label: "Plâtrier" },
  { label: "Plombier" },
  { label: "Poissonnier" },
  { label: "Potier" },
  { label: "Relieur" },
  { label: "Restaurateur d'art" },
  { label: "Sculpteur" },
  { label: "Serrurier" },
  { label: "Tapissier" },
  { label: "Tailleur" },
  { label: "Traiteur" },
  { label: "Vitrailliste" }
];

// Tableau des villes disponibles dans l'application
// Chaque objet dans le tableau représente une ville avec une étiquette
export const villes = [
  { label: "Abengourou" },
  { label: "Abidjan" },
  { label: "Adiaké" },
  { label: "Adzopé" },
  { label: "Agboville" },
  { label: "Agnibilékrou" },
  { label: "Aboisso" },
  { label: "Anyama" },
  { label: "Arrah" },
  { label: "Bondoukou" },
  { label: "Bouaflé" },
  { label: "Bouaké" },
  { label: "Bouna" },
  { label: "Boundiali" },
  { label: "Dabakala" },
  { label: "Dabou" },
  { label: "Daloa" },
  { label: "Daoukro" },
  { label: "Dimbokro" },
  { label: "Divo" },
  { label: "Duekoué" },
  { label: "Ferkessédougou" },
  { label: "Grand-Bassam" },
  { label: "Grand-Lahou" },
  { label: "Guiglo" },
  { label: "Issia" },
  { label: "Jacqueville" },
  { label: "Katiola" },
  { label: "Korhogo" },
  { label: "Lakota" },
  { label: "Man" },
  { label: "Mankono" },
  { label: "Odienné" },
  { label: "Oumé" },
  { label: "Sakassou" },
  { label: "San-Pédro" },
  { label: "Sassandra" },
  { label: "Séguéla" },
  { label: "Sinfra" },
  { label: "Soubré" },
  { label: "Tabou" },
  { label: "Tanda" },
  { label: "Tiassalé" },
  { label: "Tingréla" },
  { label: "Touba" },
  { label: "Toumodi" },
  { label: "Vavoua" },
  { label: "Yamoussoukro" },
  { label: "Zuenoula" }
];

export const payment = [
  { label: "Paiement Orange Money" },
  { label: "Paiement Moov Money" },
  { label: "Paiement MTN Money" },
  { label: "Paiement Wave" },
  { label: "Paiement Cash" },
  { label: "Paiement Carte bancaire" }
];

export const pays = [
  { label: "Afrique du Sud" },
  { label: "Algérie" },
  { label: "Angola" },
  { label: "Bénin" },
  { label: "Botswana" },
  { label: "Burkina Faso" },
  { label: "Burundi" },
  { label: "Cameroun" },
  { label: "Cap-Vert" },
  { label: "République centrafricaine" },
  { label: "Comores" },
  { label: "Congo-Brazzaville" },
  { label: "Congo-Kinshasa" },
  { label: "Côte d'Ivoire" },
  { label: "Djibouti" },
  { label: "Égypte" },
  { label: "Érythrée" },
  { label: "Eswatini" },
  { label: "Éthiopie" },
  { label: "Gabon" },
  { label: "Gambie" },
  { label: "Ghana" },
  { label: "Guinée" },
  { label: "Guinée-Bissau" },
  { label: "Guinée équatoriale" },
  { label: "Kenya" },
  { label: "Lesotho" },
  { label: "Libéria" },
  { label: "Libye" },
  { label: "Madagascar" },
  { label: "Malawi" },
  { label: "Mali" },
  { label: "Maroc" },
  { label: "Maurice" },
  { label: "Mauritanie" },
  { label: "Mozambique" },
  { label: "Namibie" },
  { label: "Niger" },
  { label: "Nigeria" },
  { label: "Ouganda" },
  { label: "Rwanda" },
  { label: "Sao Tomé-et-Principe" },
  { label: "Sénégal" },
  { label: "Seychelles" },
  { label: "Sierra Leone" },
  { label: "Somalie" },
  { label: "Soudan" },
  { label: "Soudan du Sud" },
  { label: "Tanzanie" },
  { label: "Tchad" },
  { label: "Togo" },
  { label: "Tunisie" },
  { label: "Zambie" },
  { label: "Zimbabwe" }
];

export const profil = [{ label: "Artisan" }, { label: "Client" }];
