// Tableau des métiers disponibles dans l'application
export const metiers = [
  { label: "Boucher" },
  { label: "Boulanger" },
  { label: "Carreleur" },
  { label: "Charpentier" },
  { label: "Chauffagiste" },
  { label: "Chocolatier" },
  { label: "Ciseleur" },
  { label: "Cordonnerie" },
  { label: "Coutelier" },
  { label: "Cuisinier" },
  { label: "Ébéniste" },
  { label: "Électricien" },
  { label: "Esthéticien(ne)" },
  { label: "Ferronnier" },
  { label: "Fleuriste" },
  { label: "Forgeron" },
  { label: "Graveur" },
  { label: "Horloger" },
  { label: "Imprimeur" },
  { label: "Installateur sanitaire" },
  { label: "Jardinier-paysagiste" },
  { label: "Maçon" },
  { label: "Menuisier" },
  { label: "Mécanicien automobile" },
  { label: "Modiste" },
  { label: "Orfèvre" },
  { label: "Pâtissier" },
  { label: "Peintre en bâtiment" },
  { label: "Photographe" },
  { label: "Plâtrier" },
  { label: "Plombier" },
  { label: "Poissonnier" },
  { label: "Potier" },
  { label: "Relieur" },
  { label: "Restaurateur d'art" },
  { label: "Sculpteur" },
  { label: "Serrurier" },
  { label: "Tapissier" },
  { label: "Tailleur" },
  { label: "Traiteur" },
  { label: "Vitrailliste" }
];

// Tableau des villes disponibles dans l'application
export const villes = [
  { label: "Abengourou" },
  { label: "Abidjan" },
  { label: "Abobo" },
  { label: "Adiaké" },
  { label: "Adzopé" },
  { label: "Agboville" },
  { label: "Agnibilékrou" },
  { label: "Aboisso" },
  { label: "Anyama" },
  { label: "Arrah" },
  { label: "Attécoubé" },
  { label: "Bingerville" },
  { label: "Bondoukou" },
  { label: "Bouaflé" },
  { label: "Bouaké" },
  { label: "Bouna" },
  { label: "Boundiali" },
  { label: "Cocody" },
  { label: "Dabakala" },
  { label: "Dabou" },
  { label: "Daloa" },
  { label: "Daoukro" },
  { label: "Dimbokro" },
  { label: "Divo" },
  { label: "Duekoué" },
  { label: "Ferkessédougou" },
  { label: "Gagnoa" },
  { label: "Grand-Bassam" },
  { label: "Grand-Lahou" },
  { label: "Guiglo" },
  { label: "Issia" },
  { label: "Jacqueville" },
  { label: "Katiola" },
  { label: "Kandé" },
  { label: "Korhogo" },
  { label: "Lakota" },
  { label: "Man" },
  { label: "Mankono" },
  { label: "N'zié" },
  { label: "Odienné" },
  { label: "Oumé" },
  { label: "Port-Bouët" },
  { label: "Sakassou" },
  { label: "San-Pédro" },
  { label: "Sassandra" },
  { label: "Séguéla" },
  { label: "Sinfra" },
  { label: "Soubré" },
  { label: "Tabou" },
  { label: "Tanda" },
  { label: "Tengréla" },
  { label: "Tiassalé" },
  { label: "Tingréla" },
  { label: "Touba" },
  { label: "Toumodi" },
  { label: "Treichville" },
  { label: "Vavoua" },
  { label: "Yamoussoukro" },
  { label: "Yopougon" },
  { label: "Zuenoula" }
];

// Tableau des pays disponibles dans l'application
export const pays = [{ label: "Côte d'Ivoire" }];

// Tableau des options de profil utilisateur disponibles dans l'application
export const profilOptions = [
  { id: "2", label: "Client" },
  { id: "3", label: "Artisan" }
];

// Tableau des options de sexe disponibles dans l'application
export const sexe = [{ label: "Masculin" }, { label: "Feminin" }];
